---
collections:
  - name: ansible.posix
  - name: community.sops
  - name: kubernetes.core

roles:
  - name: crc
    src: https://github.com/makeitworkcloud/ansible-role-crc
  - name: openshift_gitops_ksops
    src: https://github.com/makeitworkcloud/ansible-role-ksops
