#!/usr/bin/env ansible-playbook
---
- name: Load SOPS values
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load vars task
      community.sops.load_vars:
        file: secrets/secrets.yaml

- name: Deploy OpenShift Local (crc) with GitOps + KSOPS
  hosts: all
  gather_facts: true
  roles:
    - role: crc
      vars:
        crc_external_domain: makeitwork.cloud
        crc_argocd_app_repo: https://github.com/makeitworkcloud/kustomize-cluster.git
        crc_argocd_app_path: bootstrap
        crc_argocd_age_keys: "{{ hostvars['localhost']['age_keys'] }}"
