---
- name: Edit /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }}    api.{{ crc_external_domain | default('makeitwork.cloud') }} \
      canary-openshift-ingress-canary.apps.{{ crc_external_domain | default('makeitwork.cloud') }} \
      console-openshift-console.apps.{{ crc_external_domain | default('makeitwork.cloud') }} \
      default-route-openshift-image-registry.apps.{{ crc_external_domain | default('makeitwork.cloud') }} \
      downloads-openshift-console.apps.{{ crc_external_domain | default('makeitwork.cloud') }} host.\
      {{ crc_external_domain | default('makeitwork.cloud') }} oauth-openshift.apps.\
      {{ crc_external_domain | default('makeitwork.cloud') }}"
    state: present
  become: true
  become_user: root
