---
# tasks file for crc
- name: Running firewalld.yml
  ansible.builtin.include_tasks: firewalld.yml
- name: Running haproxy.yml
  ansible.builtin.include_tasks: haproxy.yml
- name: Running hosts.yml
  ansible.builtin.include_tasks: hosts.yml
- name: Running crc.yml
  ansible.builtin.include_tasks: crc.yml
- name: Running certs.yml
  ansible.builtin.include_tasks: certs.yml
- name: Running banner.yml
  ansible.builtin.include_tasks: banner.yml
